In [279]:
import pandas as pd
import tensorflow as tf

In [280]:
casas = pd.read_csv('/home/rayzo/Descargas/original(3).csv')

In [281]:
casas.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

In [282]:
casas_x = casas.drop('median_house_value',axis=1)


In [283]:
casas_x.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  
0      1015.0       472.0         1.4936  
1      1129.0       463.0         1.8200  
2       333.0       117.0         1.6509  
3       515.0       226.0         3.1917  
4       624.0       262.0         1.9250

In [284]:
casas_y = casas['median_income']

In [285]:
casas_y.head()

0    1.4936
1    1.8200
2    1.6509
3    3.1917
4    1.9250
Name: median_income, dtype: float64

In [286]:
from sklearn.model_selection import train_test_split


In [288]:
x_train, x_test, y_train, y_test = train_test_split(casas_x, casas_y, test_size=0.30)

In [290]:
x_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
6783     -118.30     34.18                 5.0       5492.0          1549.0   
2752     -117.70     34.06                25.0       2054.0           609.0   
10629    -120.48     35.05                24.0       2314.0           468.0   
13348    -121.93     37.73                23.0       2564.0           347.0   
12434    -121.58     37.02                27.0       2303.0           471.0   

       population  households  median_income  
6783       2997.0      1405.0         3.3205  
2752       2271.0       564.0         2.3049  
10629      1549.0       463.0         2.8203  
13348      1043.0       351.0         6.2048  
12434      1447.0       467.0         3.2019

In [291]:
x_test.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1789     -117.26     33.20                13.0       3163.0           725.0   
5950     -118.21     34.04                36.0       1825.0           479.0   
4910     -118.10     33.90                40.0       1880.0           377.0   
11368    -121.21     38.67                11.0       5500.0           956.0   
802      -117.07     33.13                33.0        555.0           165.0   

       population  households  median_income  
1789       1675.0       629.0         2.8214  
5950       2097.0       480.0         2.1862  
4910       1229.0       378.0         4.4167  
11368      2827.0       946.0         4.1071  
802         612.0       176.0         2.1786

In [292]:
y_train.head()

6783     3.3205
2752     2.3049
10629    2.8203
13348    6.2048
12434    3.2019
Name: median_income, dtype: float64

In [293]:
y_test.head()

1789     2.8214
5950     2.1862
4910     4.4167
11368    4.1071
802      2.1786
Name: median_income, dtype: float64

In [294]:
from sklearn.preprocessing import MinMaxScaler

In [295]:
normalizador = MinMaxScaler()

In [296]:
normalizador.fit(x_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [297]:
x_train = pd.DataFrame(data=normalizador.transform(x_train), columns=x_train.columns, index=x_train.index)

In [298]:
x_test = pd.DataFrame(data=normalizador.transform(x_test), columns=x_test.columns, index=x_test.index)

In [299]:
x_test.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1789    0.703815  0.070664            0.235294     0.083182        0.132358   
5950    0.608434  0.160600            0.686275     0.047905        0.087386   
4910    0.619478  0.145610            0.764706     0.049355        0.068739   
11368   0.307229  0.656317            0.196078     0.144797        0.174589   
802     0.722892  0.063169            0.627451     0.014422        0.029982   

       population  households  median_income  
1789     0.103450    0.121049       0.160101  
5950     0.129639    0.092328       0.116295  
4910     0.075773    0.072668       0.270120  
11368    0.174941    0.182151       0.248769  
802      0.037483    0.033732       0.115771

In [300]:
casas.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [301]:
longitude = tf.feature_column.numeric_column('longitude')
latitude = tf.feature_column.numeric_column('latitude')
housing_median_age = tf.feature_column.numeric_column('housing_median_age')
total_rooms = tf.feature_column.numeric_column('total_rooms')
total_bedrooms = tf.feature_column.numeric_column('total_bedrooms')
population = tf.feature_column.numeric_column('population')
households = tf.feature_column.numeric_column('households')
median_income = tf.feature_column.numeric_column('median_income')

In [302]:
columnas = [longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income]

In [303]:
funcion_entrada = tf.estimator.inputs.pandas_input_fn(x=x_train, y=y_train, batch_size=10, num_epochs=100, shuffle=True)

In [304]:
modelo = tf.estimator.DNNRegressor(hidden_units=[10,10,10], feature_columns=columnas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_model_dir': '/tmp/tmplygmo80d', '_device_fn': None, '_master': '', '_num_ps_replicas': 0, '_evaluation_master': '', '_train_distribute': None, '_global_id_in_cluster': 0, '_save_checkpoints_steps': None, '_save_summary_steps': 100, '_task_id': 0, '_keep_checkpoint_max': 5, '_num_worker_replicas': 1, '_service': None, '_tf_random_seed': None, '_session_config': None, '_task_type': 'worker', '_log_step_count_steps': 100, '_is_chief': True, '_keep_checkpoint_every_n_hours': 10000, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7faaa44c4080>}


In [305]:
modelo.train(input_fn=funcion_entrada, steps=9000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmplygmo80d/model.ckpt.
INFO:tensorflow:loss = 103.69847, step = 1
INFO:tensorflow:global_step/sec: 74.514
INFO:tensorflow:loss = 0.1778297, step = 101 (1.355 sec)
INFO:tensorflow:global_step/sec: 123.362
INFO:tensorflow:loss = 0.027053325, step = 201 (0.805 sec)
INFO:tensorflow:global_step/sec: 111.837
INFO:tensorflow:loss = 0.11031521, step = 301 (0.899 sec)
INFO:tensorflow:global_step/sec: 110.219
INFO:tensorflow:loss = 0.07684558, step = 401 (0.907 sec)
INFO:tensorflow:global_step/sec: 109.231
INFO:tensorflow:loss = 0.033489816, step = 501 (0.914 sec)
INFO:tensorflow:global_step/sec: 107.015
INFO:tensorflow:loss = 0.025534095, step = 601 (0.936 sec)
INFO:tensorflow:global_step/sec: 107.246
INFO:tens

INFO:tensorflow:loss = 9.933191e-05, step = 7801 (0.935 sec)
INFO:tensorflow:global_step/sec: 107.652
INFO:tensorflow:loss = 7.797382e-05, step = 7901 (0.939 sec)
INFO:tensorflow:global_step/sec: 104.679
INFO:tensorflow:loss = 0.0002905223, step = 8001 (0.953 sec)
INFO:tensorflow:global_step/sec: 106.103
INFO:tensorflow:loss = 7.1592e-05, step = 8101 (0.935 sec)
INFO:tensorflow:global_step/sec: 106.223
INFO:tensorflow:loss = 0.00017601046, step = 8201 (0.944 sec)
INFO:tensorflow:global_step/sec: 105.604
INFO:tensorflow:loss = 0.00021849036, step = 8301 (0.942 sec)
INFO:tensorflow:global_step/sec: 110.763
INFO:tensorflow:loss = 0.000640168, step = 8401 (0.904 sec)
INFO:tensorflow:global_step/sec: 106.945
INFO:tensorflow:loss = 0.00010036142, step = 8501 (0.943 sec)
INFO:tensorflow:global_step/sec: 110.943
INFO:tensorflow:loss = 0.00015952667, step = 8601 (0.894 sec)
INFO:tensorflow:global_step/sec: 92.162
INFO:tensorflow:loss = 0.00047452174, step = 8701 (1.085 sec)
INFO:tensorflow:glob

In [306]:
funcion_entrada_prediccion = tf.estimator.inputs.pandas_input_fn(x=x_test, batch_size=10, num_epochs=1, shuffle=False)

In [314]:
generador_predicciones = modelo.predict(funcion_entrada_prediccion)

In [315]:
predicciones = list(generador_predicciones)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmplygmo80d/model.ckpt-9000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [316]:
predicciones

[{'predictions': array([2.8202422], dtype=float32)},
 {'predictions': array([2.1849828], dtype=float32)},
 {'predictions': array([4.4175673], dtype=float32)},
 {'predictions': array([4.1113567], dtype=float32)},
 {'predictions': array([2.1810684], dtype=float32)},
 {'predictions': array([2.303427], dtype=float32)},
 {'predictions': array([3.1317697], dtype=float32)},
 {'predictions': array([4.1316547], dtype=float32)},
 {'predictions': array([4.983117], dtype=float32)},
 {'predictions': array([3.2046423], dtype=float32)},
 {'predictions': array([2.3446467], dtype=float32)},
 {'predictions': array([3.4306831], dtype=float32)},
 {'predictions': array([5.1641026], dtype=float32)},
 {'predictions': array([3.805264], dtype=float32)},
 {'predictions': array([2.8343437], dtype=float32)},
 {'predictions': array([3.1838663], dtype=float32)},
 {'predictions': array([4.8727617], dtype=float32)},
 {'predictions': array([6.688068], dtype=float32)},
 {'predictions': array([6.637755], dtype=float32)}

In [326]:
predicciones_finales = []

In [327]:
for prediccion in predicciones:
    predicciones_finales.append(prediccion['predictions'])

In [328]:
predicciones_finales

[array([2.8202422], dtype=float32),
 array([2.1849828], dtype=float32),
 array([4.4175673], dtype=float32),
 array([4.1113567], dtype=float32),
 array([2.1810684], dtype=float32),
 array([2.303427], dtype=float32),
 array([3.1317697], dtype=float32),
 array([4.1316547], dtype=float32),
 array([4.983117], dtype=float32),
 array([3.2046423], dtype=float32),
 array([2.3446467], dtype=float32),
 array([3.4306831], dtype=float32),
 array([5.1641026], dtype=float32),
 array([3.805264], dtype=float32),
 array([2.8343437], dtype=float32),
 array([3.1838663], dtype=float32),
 array([4.8727617], dtype=float32),
 array([6.688068], dtype=float32),
 array([6.637755], dtype=float32),
 array([3.7337503], dtype=float32),
 array([3.232272], dtype=float32),
 array([4.133597], dtype=float32),
 array([5.16043], dtype=float32),
 array([6.061654], dtype=float32),
 array([5.8119993], dtype=float32),
 array([3.175973], dtype=float32),
 array([5.2908325], dtype=float32),
 array([3.012738], dtype=float32),
 arr

In [329]:
from sklearn.metrics import mean_squared_log_error

In [330]:
mean_squared_error(y_test, predicciones_finales)**0.5

0.021312904601870433