In [1]:
import tensorflow as tf
import numpy as np

In [19]:
aleatorio_a = np.random.uniform(0,50,(4,4))

In [18]:
aleatorio_b = np.random.uniform(0,50,(4,4))

In [6]:
aleatorio_a

array([[46.00216932],
       [ 6.68983704],
       [16.56015017],
       [48.8454675 ]])

In [7]:
aleatorio_b

array([[28.01824746],
       [20.44654877],
       [42.70162017],
       [18.11101831]])

In [8]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [9]:
suma = a + b
multiplicacion = a * b

In [21]:
with tf.Session() as sesion:
    resultado_suma = sesion.run(suma,feed_dict={a:aleatorio_a, b:aleatorio_b})
    print(resultado_suma)

[[92.67079  43.656128 94.946884 52.374466]
 [34.06794  30.809072 37.131023 94.22684 ]
 [68.61987  61.130238 33.957916 44.580315]
 [46.721775 21.42725  54.108505 27.403511]]


In [20]:
 with tf.Session() as sesion:
    resultado_multiplicacion = sesion.run(multiplicacion,feed_dict={a:aleatorio_a, b:aleatorio_b})
    print(resultado_multiplicacion)

[[2145.4082    466.44778  2253.0032    333.20532 ]
 [ 253.19652    78.47738    57.935745 2214.167   ]
 [1074.9243    850.29816   280.8035     79.48964 ]
 [ 295.32733    47.74343   723.05115   186.98886 ]]


In [22]:
# EJEMPLO DE RED NEURONAL

In [37]:
caracteristicas = 10
neurona = 4

In [38]:
x = tf.placeholder(tf.float32,(None, caracteristicas))

In [39]:
w = tf.Variable(tf.random_normal([caract, neurona]))

In [40]:
b = tf.Variable(tf.ones([neurona]))

In [41]:
multiplicacion = tf.matmul(x,w)

In [42]:
z = tf.add(multiplicacion,b)

In [43]:
activacion = tf.sigmoid(z)

In [44]:
inicializacion = tf.global_variables_initializer()

In [45]:
valores_x = np.random.random([1,caracteristicas])

In [46]:
valores_x

array([[0.47891158, 0.57957021, 0.05214953, 0.77169822, 0.86391094,
        0.74018884, 0.08074389, 0.3573368 , 0.50519652, 0.86986176]])

In [48]:
with tf.Session() as sesion:
    sesion.run(inicializacion)
    resul = sesion.run(activacion, feed_dict={x:valores_x})

In [50]:
print(resul)

[[0.6828574 0.8889321 0.9288958 0.5411029]]
