In [2]:
import tensorflow as tf

In [6]:
print (tf.get_default_graph())

In [8]:
tensor = tf.random_uniform((5,5),0,1)

In [9]:
variable = tf.Variable(initial_value=tensor)

In [10]:
print(variable)

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32_ref>


In [11]:
inicializador = tf.global_variables_initializer()

In [15]:
with tf.Session() as sesion:
    sesion.run(inicializador)
    resultado = sesion.run(variable)

In [16]:
print(resultado)

[[9.7701550e-02 5.3139627e-01 9.8265171e-01 3.8469827e-01 4.4889545e-01]
 [8.0285406e-01 3.6098397e-01 1.4912915e-01 3.5714626e-01 2.6586962e-01]
 [4.9660599e-01 6.2906742e-04 5.6611764e-01 2.6257467e-01 3.5563350e-01]
 [9.6634066e-01 9.1611099e-01 1.5668929e-01 8.8844132e-01 5.9222114e-01]
 [1.1057854e-01 6.1770785e-01 4.4731450e-01 3.4722841e-01 1.1010265e-01]]


In [17]:
incognita = tf.placeholder(tf.float32, shape=(20,20))

In [19]:
print(incognita)

Tensor("Placeholder:0", shape=(20, 20), dtype=float32)
